export const translations = {
  en: {
    //NavBar
    "nav.explore": "Explore",
    "nav.login": "Login",
    "nav.signup": "Get Started",
    "nav.searchPlaceholder": "What do you want to learn today?",
    "nav.askBloom": "Ask Bloom",

    //Dropdown Profile
    "dropdown.myAccount": "My Account",
    "dropdown.language": "Language",
    "dropdown.settings": "Settings",
    "dropdown.helpSupport": "Help & Support",
    "dropdown.logout": "Log out",

    // Auth (Login / Signup)
    "auth.login": "Log In",
    "auth.signup": "Sign Up",
    "auth.getStarted": "Get Started",
    "auth.slogan": "Login to explore new<br>horizons of knowledge",
    "auth.loginTitle": "Log in",
    "auth.emailLabel": "Email",
    "auth.emailPlaceholder": "Input your email *",
    "auth.passwordLabel": "Password",
    "auth.passwordPlaceholder": "Input your password *",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password",
    "auth.loginBtn": "Log in",
    "auth.continueWith": "Or continue with",
    "auth.noAccount": "Don’t have an account?",
    "auth.signUpLink": "Sign up now",

    "modalLanguage.chooseLanguage": "Choose a language",

    //SideBar
    "side.home": "Home",
    "side.achivements": "Achivements",
    "side.myCourses": "My Courses",
    "side.myRoadmaps": "My Roadmaps",
    "side.certificates": "Certificates",
    "side.settings": "Settings",
    //Ask Bloom Modal
    "modalAskBloom.title": "Hello, I'm Bloom!",
    "modalAskBloom.subtitle":
      "Let Bloom build a personalized roadmap just for you. Tell me about your goals and interests, and I'll create a learning path to help you grow.",
    "modalAskBloom.startButton": "Let's Start",


    //Home Site
    "home.welcome": "Welcome back,",
    "home.subMsg": "You are doing so good my friend, keep your chin up!",
    "home.continueExploring": "Continue Exploring",
    "home.weeklyGoals": "Weekly Goals",
    "home.studyTime": "Study Time",
    "home.lessons": "Lessons",
    "home.quizzes": "Quizzes",
    "home.viewAll": "View All",
    "home.streak": "Streak",
    "home.daysOnFire": "days on fire!",
    "home.streakMsg": "Keep it up to earn \"Fire Keeper\" badge.",
    "home.recentCourses": "Recent Courses",
    "home.recommend": "Recommend For You",
    "home.lastAccess": "Last access: 3h ago",
    "home.module": "Section 3: Operators and Expressions",

    // Roadmaps
    "roadmap.title": "Roadmaps",
    "roadmap.create": "Create new roadmap",
    "roadmap.viewDetails": "View Details",
    "roadmap.lastActive": "Last active",
    "roadmap.progress": "Progress",


    // Roadmap Detail
    "roadmap.detail": "Detail",
    "roadmap.designedFor": "Designed for:",
    "roadmap.goal": "Goal:",
    "roadmap.export": "Export as image",
    "roadmap.share": "Share",
    "roadmap.months": "Months",
    "roadmap.difficulty": "Difficulty",
    "roadmap.skills": "Skills",
    "roadmap.recCourses": "Recommended Courses",
    "status.done": "Done",
    "status.studying": "Studying",
    "status.notStarted": "Not Started",

    //Course Card
    "course.beginner": "Beginner",

    "course.students": "Students",
    "course.price": "299,000 VND",
    "course.progress": "Progress",
    "course.addToCart": "Add to Cart",

    // Footer
    "footer.slogan": "Effortless learning, maximum efficiency. A minimalist e-learning platform for Gen Z.<br>Just chill and study.",
    "footer.explore": "Explore",
    "footer.newCourses": "New Courses",
    "footer.roadmap": "Roadmap",
    "footer.mentors": "Top Mentors",
    "footer.blog": "Blog",
    "footer.resources": "Resources",
    "footer.freeDocs": "Free Documents",
    "footer.community": "Community",
    "footer.events": "Events & Workshop",
    "footer.tools": "Study Tools",
    "footer.chillMode": "Chill Mode",
    "footer.lofi": "Lofi Radio Station",
    "footer.turnOnMusic": "Turn on music and focus now.",
    "footer.copyright": "© 2025 Bloom E-Learning. Designed properly for HCI.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",

    // Explore Page
    "explore.title": "Explore",
    "explore.editorsPick": "Editor's Pick This Month",
    "explore.personalized": "Picked for you",
    "explore.featured": "Featured Courses",
    "explore.trending": "Trending Now",
    "explore.topics": "Topics",
    "explore.viewDetails": "View Details",
    "explore.detail": "Detail",

    // Filter Modal
    "filter.title": "Filter",
    "filter.clear": "Clear All",
    "filter.apply": "Apply Filter",
    "filter.level": "Level",
    "filter.rating": "Rating",
    "filter.duration": "Duration",
    "filter.language": "Language",
    "filter.allLevels": "All Levels",
    "filter.intermediate": "Intermediate",
    "filter.expert": "Expert",
    "filter.price": "Price", // Backup if needed

    // My Courses
    "myCourses.tab.learning": "Learning",
    "myCourses.tab.saved": "Saved",
    "myCourses.lastAccessed": "Last accessed",
    "myCourses.completed": "Completed",
    "myCourses.continue": "Continue",
    "myCourses.lessons": "lessons",

    // Learning Page
    "learning.breadcrumb": "Learning Space",
    "course.content": "Course Content",
    "course.overview": "Overview",
    "course.resources": "Resources",
    "course.discussion": "Discussion",
    "course.section1": "Section 1: Introduction to Python",
    "course.section2": "Section 2: Basic Syntax and Data Types",
    "course.section3": "Section 3: Operators and Expressions",
    "course.section4": "Section 4: Control Flow",
    "course.section5": "Section 5: Functions",

    // Certificates
    "certificates.title": "Certificates",
    "certificates.noCert": "No certificates yet",
    "certificates.download": "Download",
    "certificates.viewDetails": "View Details",
    "certificates.earned": "Certificates Earned",
    "certificates.skills": "Certified Skills",
    "certificates.completed": "Courses Completed",

    // Achievements (Gamification)
    "achievements.title": "Achievements",
    "achievements.badges": "Badges",
    "achievements.stats": "Learning Stats",
    "achievements.streak": "Streak",
    "achievements.level": "Level",
    "achievements.xp": "XP",
    "achievements.leaderboard": "Leaderboard",
    "achievements.locked": "Locked",
    "achievements.miniComp": "Mini Challenge",
    "achievements.monthComp": "Monthly Tournament",
    "achievements.medals": "Medals",
    "achievements.join": "Join Now",
    "achievements.timeLeft": "Time Left",
    "achievements.leaderboardTitle": "Top Learners",

    // Course Detail
    "courseDetail.bestseller": "Bestseller",
    "courseDetail.updated": "Last updated",
    "courseDetail.created": "Created by",
    "courseDetail.ratings": "ratings",
    "courseDetail.students": "students",
    "courseDetail.lang": "English",
    "courseDetail.whatLearn": "What you'll learn",
    "courseDetail.requirements": "Requirements",
    "courseDetail.desc": "Description",
    "courseDetail.mentors": "Mentors",
    "courseDetail.reviews": "Reviews",
    "courseDetail.addToCart": "Add to Cart",
    "courseDetail.buyNow": "Buy Now",
    "courseDetail.includes": "This course includes:",
    "courseDetail.hours": "hours on-demand video",
    "courseDetail.articles": "articles",
    "courseDetail.resources": "downloadable resources",
    "courseDetail.access": "Full lifetime access",
    "courseDetail.mobile": "Access on mobile and TV",
    "courseDetail.cert": "Certificate of completion",
    "courseDetail.related": "Related Topics",
    "courseDetail.showAllReviews": "Show all reviews",
    "courseDetail.reviewsCount": "123,000 Reviews",
    "courseDetail.preview": "Preview this course",
    "courseDetail.hoursVideo": "hours video",
    "courseDetail.resourcesShort": "resources",
    "courseDetail.mobileShort": "Mobile & TV",
    "courseDetail.certShort": "Certificate",

    // Onboarding (Ask Bloom)
    "onboarding.title": "Ask Bloom",
    "onboarding.result": "Your Roadmap",
    "onboarding.step": "Step",
    "onboarding.back": "Back",
    "onboarding.next": "Next",
    "onboarding.finish": "Finish",
    "onboarding.analyzing": "Bloom is analyzing your answers...",
    "onboarding.insight": "Based on what you told me, you seem to have a strong passion for logical thinking and problem-solving.",
    "onboarding.resultTitle": "Here is your personalized roadmap",
    "onboarding.save": "Save Roadmap",
    "onboarding.savedMsg": "Roadmap saved to your library!",
    "onboarding.inputLabel": "Tell me more about the specific skill or job you want to aim for:",
    "onboarding.inputPlaceholder": "Please describe in detail the skills, major, or career you are interested in...",
    "onboarding.reset": "Start Over",
    "roadmap.recCourses": "Recommended Courses",
    "status.notStarted": "Not Started",

    // Onboarding Questions
    "onboarding.q1.title": "What is your primary learning goal?",
    "onboarding.q1.opt1": "Start a new career",
    "onboarding.q1.opt2": "Improve existing skills",
    "onboarding.q1.opt3": "Learn for fun",
    "onboarding.q1.opt4": "Academic support",

    "onboarding.q2.title": "How much time can you spend daily?",
    "onboarding.q2.opt1": "15-30 minutes",
    "onboarding.q2.opt2": "1 hour",
    "onboarding.q2.opt3": "2-3 hours",
    "onboarding.q2.opt4": "Unlimited",

    "onboarding.q3.title": "What is your preferred learning style?",
    "onboarding.q3.opt1": "Video tutorials",
    "onboarding.q3.opt2": "Reading & Documentation",
    "onboarding.q3.opt3": "Interactive quizzes",
    "onboarding.q3.opt4": "Project-based",
  },
  vi: {
    //NavBar
    "nav.explore": "Khám Phá",
    "nav.login": "Đăng Nhập",
    "nav.signup": "Bắt Đầu",
    "nav.searchPlaceholder": "Hôm nay bạn muốn học gì?",
    "nav.askBloom": "Hỏi Bloom",

    //Dropdown Profile
    "dropdown.myAccount": "Tài Khoản Của Tôi",
    "dropdown.language": "Ngôn Ngữ",
    "dropdown.settings": "Cài Đặt",
    "dropdown.helpSupport": "Trợ Giúp & Hỗ Trợ",
    "dropdown.logout": "Đăng Xuất",

    // Auth (Login / Signup)
    "auth.login": "Đăng Nhập",
    "auth.signup": "Đăng Ký",
    "auth.getStarted": "Bắt Đầu",
    "auth.slogan": "Đăng nhập để khám phá<br>chân trời kiến thức mới",
    "auth.loginTitle": "Đăng nhập",
    "auth.emailLabel": "Email",
    "auth.emailPlaceholder": "Nhập email của bạn *",
    "auth.passwordLabel": "Mật khẩu",
    "auth.passwordPlaceholder": "Nhập mật khẩu của bạn *",
    "auth.rememberMe": "Ghi nhớ đăng nhập",
    "auth.forgotPassword": "Quên mật khẩu",
    "auth.loginBtn": "Đăng nhập",
    "auth.continueWith": "Hoặc tiếp tục với",
    "auth.noAccount": "Chưa có tài khoản?",
    "auth.signUpLink": "Đăng ký ngay",

    "modalLanguage.chooseLanguage": "Chọn một ngôn ngữ",

    //SideBar
    "side.home": "Trang Chủ",
    "side.achivements": "Thành Tựu",
    "side.myCourses": "Khóa Học Của Tôi",
    "side.myRoadmaps": "Lộ Trình Của Tôi",
    "side.certificates": "Chứng Chỉ",
    "side.settings": "Cài Đặt",

    //Ask Bloom Modal
    "modalAskBloom.title": "Xin chào, mình là Bloom đây!",
    "modalAskBloom.subtitle":
      "Hãy để Bloom tạo một lộ trình học tập cá nhân hóa dành riêng cho bạn nhé. Hãy cho mình biết về mục tiêu và sở thích của bạn, mình sẽ xây dựng một con đường học tập giúp bạn phát triển.",
    "modalAskBloom.startButton": "Bắt Đầu Nào",

    //Home Site
    "home.welcome": "Chào mừng trở lại,",
    "home.subMsg": "Bạn đang làm rất tốt, hãy tiếp tục cố gắng nhé!",
    "home.continueExploring": "Tiếp Tục Học",
    "home.weeklyGoals": "Mục Tiêu Tuần",
    "home.studyTime": "Thời Gian Học",
    "home.lessons": "Bài Học",
    "home.quizzes": "Bài Kiểm Tra",
    "home.viewAll": "Xem Tất Cả",
    "home.streak": "Chuỗi Khám Phá",
    "home.daysOnFire": "ngày rực lửa!",
    "home.streakMsg": "Duy trì để nhận huy hiệu \"Người Giữ Lửa\".",
    "home.recentCourses": "Khóa Học Gần Đây",
    "home.recommend": "Gợi Ý Cho Bạn",
    "home.lastAccess": "Truy cập: 3h trước",
    "home.module": "Section 3: Operators and Expressions",

    // Roadmaps
    "roadmap.title": "Lộ trình",
    "roadmap.create": "Tạo lộ trình mới",
    "roadmap.viewDetails": "Xem chi tiết",
    "roadmap.lastActive": "Hoạt động lần cuối",
    "roadmap.progress": "Tiến độ",




    // Roadmap Detail
    "roadmap.detail": "Chi Tiết",
    "roadmap.designedFor": "Thiết kế cho:",
    "roadmap.goal": "Mục tiêu:",
    "roadmap.export": "Xuất ảnh",
    "roadmap.share": "Chia sẻ",
    "roadmap.months": "Tháng",
    "roadmap.difficulty": "Độ khó",
    "roadmap.skills": "Kỹ năng",
    "roadmap.recCourses": "Khóa học gợi ý",
    "status.done": "Hoàn thành",
    "status.studying": "Đang học",
    "status.notStarted": "Chưa bắt đầu",

    //Course Card
    "course.beginner": "Người Mới",

    "course.students": "Học Viên",
    "course.price": "299,000 đ",
    "course.progress": "Tiến độ",
    "course.addToCart": "Thêm vào giỏ",

    // Footer
    "footer.slogan": "Học tập nhẹ nhàng, hiệu quả tối đa. Nền tảng E-learning phong cách tối giản dành cho Gen Z.<br>Just chill and study.",
    "footer.explore": "Khám Phá",
    "footer.newCourses": "Khóa học Mới",
    "footer.roadmap": "Lộ trình học",
    "footer.mentors": "Mentors xịn",
    "footer.blog": "Blog chia sẻ",
    "footer.resources": "Tài Nguyên",
    "footer.freeDocs": "Tài liệu miễn phí",
    "footer.community": "Cộng đồng",
    "footer.events": "Sự kiện & Workshop",
    "footer.tools": "Công cụ học tập",
    "footer.chillMode": "Chill Mode",
    "footer.lofi": "Lofi Radio Station",
    "footer.turnOnMusic": "Bật nhạc, tập trung học bài ngay thôi.",
    "footer.copyright": "© 2025 Bloom E-Learning. Designed properly for HCI.",
    "footer.privacy": "Quyền riêng tư",
    "footer.terms": "Điều khoản",
    "footer.cookies": "Cookies",

    // Explore Page
    "explore.title": "Khám Phá",
    "explore.editorsPick": "Lựa chọn của biên tập viên",
    "explore.personalized": "Dành riêng cho bạn",
    "explore.featured": "Khóa học nổi bật",
    "explore.trending": "Xu hướng",
    "explore.topics": "Chủ đề",
    "explore.viewDetails": "Xem chi tiết",
    "explore.detail": "Chi Tiết",

    // Filter Modal
    "filter.title": "Bộ Lọc",
    "filter.clear": "Xóa tất cả",
    "filter.apply": "Áp dụng",
    "filter.level": "Cấp độ",
    "filter.rating": "Đánh giá",
    "filter.duration": "Thời lượng",
    "filter.language": "Ngôn ngữ",
    "filter.allLevels": "Tất cả cấp độ",
    "filter.intermediate": "Trung bình",
    "filter.expert": "Chuyên gia",
    "filter.price": "Giá", // Backup if needed

    // My Courses
    "myCourses.tab.learning": "Đang học",
    "myCourses.tab.saved": "Đã lưu",
    "myCourses.lastAccessed": "Truy cập",
    "myCourses.completed": "Đã học",
    "myCourses.continue": "Tiếp tục",
    "myCourses.lessons": "bài",

    // Learning Page
    "learning.breadcrumb": "Góc học tập",
    "course.content": "Nội dung khóa học",
    "course.overview": "Tổng quan",
    "course.resources": "Tài liệu",
    "course.discussion": "Thảo luận",
    "course.section1": "Chương 1: Introduction to Python",
    "course.section2": "Chương 2: Basic Syntax and Data Types",
    "course.section3": "Chương 3: Operators and Expressions",
    "course.section4": "Chương 4: Control Flow",
    "course.section5": "Chương 5: Functions",

    // Certificates
    "certificates.title": "Chứng Chỉ",
    "certificates.noCert": "Chưa có chứng chỉ nào",
    "certificates.download": "Tải Xuống",
    "certificates.viewDetails": "Xem Chi Tiết",
    "certificates.earned": "Chứng Chỉ Đã Nhận",
    "certificates.skills": "Kỹ Năng Đã Nhận Chứng Chỉ",
    "certificates.completed": "Khóa Học Đã Hoàn Thành",

    // Achievements (Gamification)
    "achievements.title": "Thành Tựu",
    "achievements.badges": "Huy Hiệu",
    "achievements.stats": "Thống Kê Học Tập",
    "achievements.streak": "Chuỗi Thắng",
    "achievements.level": "Cấp Độ",
    "achievements.xp": "Kinh Nghiệm",
    "achievements.leaderboard": "Bảng Xếp Hạng",
    "achievements.locked": "Chưa mở khóa",
    "achievements.miniComp": "Thử Thách Nhanh",
    "achievements.monthComp": "Giải Đấu Tháng",
    "achievements.medals": "Huy Chương",
    "achievements.join": "Tham Gia Ngay",
    "achievements.timeLeft": "Thời gian còn lại",
    "achievements.leaderboardTitle": "Bảng Xếp Hạng",

    // Course Detail
    "courseDetail.bestseller": "Bán chạy nhất",
    "courseDetail.updated": "Cập nhật lần cuối",
    "courseDetail.created": "Tạo bởi",
    "courseDetail.ratings": "đánh giá",
    "courseDetail.students": "học viên",
    "courseDetail.lang": "Tiếng Anh",
    "courseDetail.whatLearn": "Bạn sẽ học được gì",
    "courseDetail.requirements": "Yêu cầu",
    "courseDetail.desc": "Mô tả",
    "courseDetail.mentors": "Giảng viên",
    "courseDetail.reviews": "Đánh giá",
    "courseDetail.addToCart": "Thêm vào giỏ",
    "courseDetail.buyNow": "Mua ngay",
    "courseDetail.includes": "Khóa học bao gồm:",
    "courseDetail.hours": "giờ video theo yêu cầu",
    "courseDetail.articles": "bài viết",
    "courseDetail.resources": "tài nguyên tải xuống",
    "courseDetail.access": "Truy cập trọn đời",
    "courseDetail.mobile": "Truy cập trên mobile và TV",
    "courseDetail.cert": "Chứng chỉ hoàn thành",
    "courseDetail.related": "Chủ đề liên quan",
    "courseDetail.showAllReviews": "Xem tất cả đánh giá",
    "courseDetail.reviewsCount": "123,000 Đánh giá",
    "courseDetail.preview": "Xem trước khóa học",
    "courseDetail.hoursVideo": "giờ video",
    "courseDetail.resourcesShort": "tài nguyên",
    "courseDetail.mobileShort": "Mobile & TV",
    "courseDetail.certShort": "Chứng chỉ",

    // Onboarding (Ask Bloom)
    "onboarding.title": "Hỏi Bloom",
    "onboarding.result": "Lộ Trình Của Bạn",
    "onboarding.step": "Bước",
    "onboarding.back": "Quay lại",
    "onboarding.next": "Tiếp theo",
    "onboarding.finish": "Hoàn thành",
    "onboarding.analyzing": "Bloom đang phân tích câu trả lời của bạn...",
    "onboarding.insight": "Dựa trên những gì bạn chia sẻ, dường như bạn có niềm đam mê lớn với tư duy logic và giải quyết vấn đề.",
    "onboarding.resultTitle": "Đây là lộ trình dành riêng cho bạn",
    "onboarding.save": "Lưu lộ trình",
    "onboarding.savedMsg": "Đã lưu lộ trình vào thư viện!",
    "onboarding.inputLabel": "Mô tả chi tiết hơn về kỹ năng hoặc công việc bạn muốn hướng tới:",
    "onboarding.inputPlaceholder": "Hãy mô tả chi tiết thêm về kỹ năng, chuyên ngành, nghề nghiệp bạn đang quan tâm...",
    "onboarding.reset": "Làm lại",
    "roadmap.recCourses": "Khóa học đề xuất",
    "status.notStarted": "Chưa bắt đầu",

    // Onboarding Questions
    "onboarding.q1.title": "Mục tiêu học tập chính của bạn là gì?",
    "onboarding.q1.opt1": "Bắt đầu nghề nghiệp mới",
    "onboarding.q1.opt2": "Cải thiện kỹ năng hiện tại",
    "onboarding.q1.opt3": "Học cho vui thôi",
    "onboarding.q1.opt4": "Hỗ trợ việc học ở trường",

    "onboarding.q2.title": "Bạn có thể dành bao nhiêu thời gian mỗi ngày?",
    "onboarding.q2.opt1": "15-30 phút",
    "onboarding.q2.opt2": "1 tiếng",
    "onboarding.q2.opt3": "2-3 tiếng",
    "onboarding.q2.opt4": "Không giới hạn",

    "onboarding.q3.title": "Phong cách học tập yêu thích của bạn là gì?",
    "onboarding.q3.opt1": "Video hướng dẫn",
    "onboarding.q3.opt2": "Đọc tài liệu",
    "onboarding.q3.opt3": "Câu hỏi tương tác",
    "onboarding.q3.opt4": "Làm dự án thực tế",
  },
};
